### ISSUE TITLE
react and react-dom version conflicts

### ISSUE THREAD

**Issue by tiamed** [dai-shi/katachidraw#34]
When using alongside expo compatible dependencies, the `react` and `react-dom` version is pinned to ^17.0.1
This library is pinned to 17.0.2, which causes version mismatch and crashes expo driven app.

Suggested solution:
move `react` and `react-dom` to peerDepencies and devDependencies

**Comment by dai-shi** [comment]
sounds great.

**Comment by dai-shi** [comment]
Published: https://www.npmjs.com/package/katachidraw/v/0.4.1
